### PR TITLE
Support PHP 8.1 and PHP 8.2

### PR DESCRIPTION
**Pull request by craig410**

### CODE REVIEW

**Comment by craig410** [comment]
@acoulton Green on 8.1 and 8.2 default builds but not on the lowest. Latest doctrine/orm is 2.13.3 but unless we take a dependency on doctrine/dbal too composer is finding an older version that doesn't work. WDYT?

**Comment by acoulton** [comment]
Hmm that's dull. Maybe rather than add a `require` we could add a `conflicts` for all versions of doctrine/dbal below the earliest one that works?

In theory that will make the --lowest builds install the newer one, but without us getting into a circular dependency thing when we want to bump the `require`d version elsewhere.

**Comment by acoulton** [comment]
FYI I just noticed that kohana-doctrine2 requires `"doctrine/dbal": "^2"` as I *think* there may have been BC breaks in 3. 

So looks like we'll either need to bump that (which may need to be a 2.x of kohana-d2 so we can bring it into projects individually) unless there is any `2.x` version of dbal that will work with a looser/lower conflicts here?

**Comment by craig410** [comment]
Oh that's very dull. No, I tried my whole way up the 2.x series. 

We can try bumping kohana-doctrine2 and then find out when we get to the projects using it. I'll come back to it last

**Pull request merged**
